config/routes.rb
Rails.application.routes.draw do
  resources :daties
  resources :links
  devise_for :users
  root to: "channel#index"
  post 'message', to: 'messages#create'
  get 'messages', to: 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daty.rb
class Daty < ApplicationRecord
  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, dependent: :destroy
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(40) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy
  has_many :links, dependent: :destroy
  has_many :daties, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channel_controller.rb
class ChannelController < ApplicationController
  before_action :authenticate_user!

  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/daties_controller.rb
class DatiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_daty, only: [:show, :edit, :update, :destroy]

  # GET /daties
  # GET /daties.json
  def index
    @daties = Daty.all.order(updated_at: :desc)
  end

  # GET /daties/1
  # GET /daties/1.json
  def show
  end

  # GET /daties/new
  def new
    @daty = Daty.new
  end

  # GET /daties/1/edit
  def edit
  end

  # POST /daties
  # POST /daties.json
  def create
    @daty = current_user.daties.build(daty_params)

    respond_to do |format|
      if @daty.save
        format.html { redirect_to @daty, notice: 'Daty was successfully created.' }
        format.json { render :show, status: :created, location: @daty }
      else
        format.html { render :new }
        format.json { render json: @daty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daties/1
  # PATCH/PUT /daties/1.json
  def update
    respond_to do |format|
      if @daty.update(daty_params)
        format.html { redirect_to @daty, notice: 'Daty was successfully updated.' }
        format.json { render :show, status: :ok, location: @daty }
      else
        format.html { render :edit }
        format.json { render json: @daty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daties/1
  # DELETE /daties/1.json
  def destroy
    @daty.destroy
    respond_to do |format|
      format.html { redirect_to daties_url, notice: 'Daty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daty
      @daty = Daty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daty_params
      params.require(:daty).permit(:start_date, :end_date, :localisation)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all.order(created_at: :desc)
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:body)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = Message.all
  end

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", content: message_render(message)
    else
      redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message, user_id: message.user_id})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channel/index.html.erb
<div class="container-fluid h-85">
  <div class="row justify-content-center h-85">
    <div class="col-md-12 col-xl-6 chat">
      <div class="card">
        <div class="card-body msg_card_body" id="messages">
          <div class="feed" id="msg">
            <%= render @messages %>
          </div>
        </div>
        <div class="card-footer">
        <%= form_for(@message, remote: true, html: {class: "input-group", role: "form"}, url: message_path) do |f| %>
          <div class="input-group-append">
            <span class="input-group-text attach_btn"><i class="fas fa-paperclip"></i></span>
          </div>
          <%= f.text_field :body, placeholder: "Napisz wiadomość...", id: "message_content", autocomplete: "off", class: "form-control type_msg" %>
          <div class="input-group-append">
            <%= f.button '<i class="fas fa-location-arrow"></i>'.html_safe, class: 'input-group-text send_btn' %>
          </div>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/daties/_form.html.erb
<%= form_with(model: daty, local: true) do |form| %>
  <div class="field">
    <%= form.label 'Początek' %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label 'Koniec' %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label 'Lokalizacja' %>
    <%= form.text_field :localisation %>
  </div>

  <div class="actions">
    <%= form.submit 'Utwórz' %>
  </div>
<% end %>

app/views/daties/edit.html.erb
<h1>Editing Daty</h1>

<%= render 'form', daty: @daty %>

<%= link_to 'Pokaż', @daty %> |
<%= link_to 'Cofnij', daties_path %>

app/views/daties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daty</h1>

<table>
  <thead>
    <tr>
      <th>Początek</th>
      <th>Koniec</th>
      <th>Lokalizacja</th>
      <th>Użytkownik</th>
      <th>Czas modyfikacji</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daties.each do |daty| %>
      <tr>
        <td><%= daty.start_date %></td>
        <td><%= daty.end_date %></td>
        <td><%= daty.localisation %></td>
        <td><%= daty.user.email %></td>
        <td><%= time_ago_in_words(daty.updated_at) %></td>
        <td><%= link_to 'Pokaż', daty %></td>
        <td><%= link_to 'Edytuj', edit_daty_path(daty) %></td>
        <td><%= link_to 'Usuń', daty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nowa data', new_daty_path %>

app/views/daties/new.html.erb
<h1>Nowa data</h1>

<%= render 'form', daty: @daty %>

<%= link_to 'Cofnij', daties_path %>

app/views/daties/show.html.erb
<p>
  <strong>Początek:</strong>
  <%= @daty.start_date %>
</p>

<p>
  <strong>Koniec:</strong>
  <%= @daty.end_date %>
</p>

<p>
  <strong>Lokalizacja:</strong>
  <%= @daty.localisation %>
</p>

<p>
  <strong>Użytkownik:</strong>
  <%= @daty.user_id %>
</p>

<%= link_to 'Edytuj', edit_daty_path(@daty) %> |
<%= link_to 'Cofnij', daties_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/shared/navbar' %>
    <div class='container'>
    <%= render 'layouts/shared/message' %>
      <%= yield %>
    </div>
</html>

app/views/layouts/shared/_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <!--<div class="alert alert-<%#= name.to_s == 'notice' ? 'success' : 'danger' %>">-->
    <div class="ui <%= name.to_s == 'notice' ? 'positive' : 'negative' %> message">
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Message Me', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Linki', links_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Daty', daties_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'All messages', messages_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class='fa fa-user'></i>
          <%= current_user.email %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <div class="field">
    <%= form.label 'Link' %>
    <%= form.text_field :body %>
  </div>

  <div class="actions">
    <%= form.submit 'Utwórz' %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Pokaż', @link %> |
<%= link_to 'Cofnij', links_path %>

app/views/links/index.html.erb
<h1>Linki</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Użytkownik</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link_to time_ago_in_words(link.created_at), link.body, target: link.body %></td>
        <td><%= link.user.email %></td>
        <td><%= link_to 'Edytuj', edit_link_path(link) %></td>
        <td><%= link_to 'Usuń', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nowy Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Cofnij', links_path %>

app/views/links/show.html.erb
<p>
  <strong>Link:</strong>
  <%= @link.body %>
</p>

<p>
  <strong>Użytkownik:</strong>
  <%= @link.user.email %>
</p>

<%= link_to 'Edytuj', edit_link_path(@link) %> |
<%= link_to 'Cofnij', links_path %>

app/views/messages/_message.html.erb
<% if current_user == message.user %>
  <div class="d-flex justify-content-end mb-4">
  <div class="msg_cotainer_send">
<% else %>
  <div class="d-flex justify-content-start mb-4">
  <div class="msg_cotainer">
<% end %>
    <%= message.body %>
    <span class="msg_time_send"><%= time_ago_in_words(message.created_at) %> ago</span>
  </div>
</div>

app/views/messages/index.html.erb
<div class="grid">
  <div class="mobile only sixteen wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="msg">
          <%= render @messages %>
        </div>
      </div>
    </div>
  </div>
</div>